[package]
name = "mmime"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@users.noreply.github.com>"]
edition = "2018"
license = "MIT"

[dependencies]
libc = "0.2.54"
c2rust-bitfields = "0.1.0"
charset = "0.1.2"
memmap = "0.7.0"
